### ISSUE TITLE
Restructure information

### ISSUE THREAD

**Issue by Benjaneb** [datasektionen/bawang-content#465]
The structure is very confusing and it's often hard to find certain things. Therefore:
- Merge sektionen/sektionsbilen/ and sektionen/lokalbokning/ into just sektionen/bokning/
- Move content in organisation/ into sektionen/
- Move namnder/revisorer/ and namnder/karfullmaktige/ to sektionen/
- Potentially rename naringsliv/ to projekt/ to include all projects and then add contacts for sponsored projects under a new folder in kontakt/

**Comment by mathiasmagnusson** [comment]
I don't think we should rename naringsliv to projekt, since some of the projects under there are committees (nämnder) and the only information under there seems to be about sponsoring them. Not sure what we should do with that page though since i agree that having that directory doesn't make that much sense.

**Comment by Herkarl** [comment]
The (or a) point of having the "näringsliv" page, from what I've gathered" is to have an easy and clear path for companies that are interested in collaborating/sponsoring to find any relevant information for them. Which seems to be fairly standard practice among chapter websites from what I've seen.

Which I think is a reasonable thing. But might be worth talking to D-NOK if you want to change it.
